structure(list(url = "https://geo.vliz.be/geoserver/Emodnetbio/wcs?service=WCS&version=2.0.1&coverageId=Emodnetbio__cal_fin_19582016_L1_err&subset=Lat(40,42)&subset=Long(0,2)&subset=time(%221963-11-16T01:00:00%22)&format=image/tiff&Rangesubset=Relative%20error&request=GetCoverage", 
    status_code = 500L, headers = structure(list(`x-content-type-options` = "nosniff", 
        `x-frame-options` = "SAMEORIGIN", `content-security-policy` = "base-uri 'self'; form-action 'self'; default-src 'none'; child-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self';, frame-ancestors 'self';", 
        `access-control-allow-origin` = "*", `content-disposition` = "inline; filename=Emodnetbio__cal_fin_19582016_L1_err.tif", 
        `content-encoding` = "gzip", `content-type` = "application/xml", 
        `transfer-encoding` = "chunked", date = "Fri, 13 Jun 2025 08:33:45 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 500L, version = "HTTP/1.1", 
        headers = structure(list(`x-content-type-options` = "nosniff", 
            `x-frame-options` = "SAMEORIGIN", `content-security-policy` = "base-uri 'self'; form-action 'self'; default-src 'none'; child-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self';, frame-ancestors 'self';", 
            `access-control-allow-origin` = "*", `content-disposition` = "inline; filename=Emodnetbio__cal_fin_19582016_L1_err.tif", 
            `content-encoding` = "gzip", `content-type` = "application/xml", 
            `transfer-encoding` = "chunked", date = "Fri, 13 Jun 2025 08:33:45 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?><ows:ExceptionReport xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:ows=\"http://www.opengis.net/ows/2.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"2.0.0\" xsi:schemaLocation=\"http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd\">\n  <ows:Exception exceptionCode=\"NoApplicableCode\">\n    <ows:ExceptionText>java.lang.RuntimeException: DataBuffer must have getOffsets().length equal to 1 or numBands.\nDataBuffer must have getOffsets().length equal to 1 or numBands.</ows:ExceptionText>\n  </ows:Exception>\n</ows:ExceptionReport>\n"), 
    date = structure(1749803625, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.7e-05, 
    connect = 0, pretransfer = 0.000122, starttransfer = 0.129535, 
    total = 0.129716)), class = "response")
