---
title: "Download Coverages"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(httptest)
start_vignette("get-cov")
```

```{r setup}
library(EMODnetWCS)
```



```{r}
wcs <- emdn_init_wcs_client(service = "biology")

```


```{r}
coverage_ids <- emdn_get_coverage_ids(wcs)
coverage_ids
```


```{r}
coverage_id <- coverage_ids[3]
coverage_id

bbox <- c(xmin = 1.5, 
          ymin = 53,
          xmax = 6.5, 
          ymax = 58)
```

# Subset using a bounding box

```{r}
cov_1 <- emdn_get_coverage(wcs,
                  coverage_id = coverage_id,
                  bbox = bbox)

cov_1
```

```{r}
terra::plot(cov_1)
```



## Subset using a bounding box and specific timepoints


```{r}
temp_coefs <- emdn_get_coverage_dim_coefs(wcs = wcs,
                            coverage_ids = coverage_id,
                            type = "temporal")

timepoints <- head(temp_coefs[[1]], 3)
timepoints
```


```{r}
cov_2 <- emdn_get_coverage(wcs,
                  coverage_id = coverage_id,
                  bbox = bbox,
                  time = timepoints)
```

```{r}
cov_2
```


```{r}
terra::plot(cov_2)
```




## Subset using a bounding box and a specific band

```{r}
emdn_get_coverage(wcs, 
                  coverage_id = coverage_id,
                  bbox = bbox,
                  rangesubset = "Relative error") |> terra::plot()
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
fs::dir_ls(type = "file", glob = "*.tif") |>
    fs::file_delete()
```


```{r cov-stop-recording, include=FALSE}
end_vignette()
```
